[templates]
zshrc = "~/.zshrc"
xinitrc = "~/.xinitrc"
i3 = "~/.config/i3/config"
sshconfig = "~/.ssh/config"
xresources = "~/.Xresources"
nvim = "~/.config/nvim/init.vim"
compton = "~/.config/compton.conf"
termite = "~/.config/termite/config"
libfm = "~/.config/libfm/libfm.conf"
neofetch = "~/.config/neofetch/config"
lemonconfig = "~/.config/undeadlemon/config.toml"
pcmanfm = "~/.config/pcmanfm/default/pcmanfm.conf"

scripts = "~/Scripts"
lemonimgs = "~/.config/undeadlemon/imgs"

test = "~/test"

[sqldbs]
stylish = "~/.mozilla/firefox/yi22gkil.dev-edition-default/stylish.sqlite"

[variables]
font = "Fira Sans"
monofont = "Fira Mono"
iconfont = "FontAwesome"
color00 = "#121212"
color01 = "#ac4142"
color02 = "#90a959"
color03 = "#f4bf75"
color04 = "#6a9fb5"
color05 = "#aa759f"
color06 = "#75b5aa"
color07 = "#616161"
color08 = "#262626"
color09 = "#702020"
color10 = "#1b5e20"
color11 = "#f9a825"
color12 = "#0d47a1"
color13 = "#a4148c"
color14 = "#006064"
color15 = "#9e9e9e"
