dotfiles = [
    { template = "zshrc", target = "~/.zshrc" },
    { template = "xinitrc", target = "~/.xinitrc" },
    { template = "i3", target = "~/.config/i3/config" },
    { template = "ssh", target = "~/.ssh/config" },
    { template = "Xresources", target = "~/.Xresources" },
    { template = "n.vim", target = "~/.config/nvim/init.vim" },
    { template = "compton", target = "~/.config/compton.conf" },
    { template = "termite", target = "~/.config/termite/config" },
    { template = "lemonconfig", target = "~/.config/undeadlemon/config.toml" },
    { template = "Scripts", target = "~/Scripts" },
    { template = "lemonimgs", target = "~/.config/undeadlemon/imgs" },
    { template = "stylish", target = "~/.mozilla/firefox/yi22gkil.dev-edition-default/stylish.sqlite" }
]

[variables]
font = "Fira Sans"
monofont = "Fira Mono"
iconfont = "FontAwesome"
color00 = "#1b1b1b"
color01 = "#ac4142"
color02 = "#90a959"
color03 = "#f4bf75"
color04 = "#6a9fb5"
color05 = "#aa759f"
color06 = "#75b5aa"
color07 = "#616161"
color08 = "#262626"
color09 = "#702020"
color10 = "#1b5e20"
color11 = "#f9a825"
color12 = "#0d47a1"
color13 = "#a4148c"
color14 = "#006064"
color15 = "#9e9e9e"
color232 = "#121212"
color235 = "#303030"
color236 = "#3a3a3a"
color237 = "#444444"
color238 = "#4c4c4c"
color239 = "#565656"
color240 = "#616161"
color241 = "#6a6a6a"
color242 = "#747474"
color243 = "#7e7e7e"
color244 = "#888888"
color245 = "#929292"
color247 = "#a6a6a6"
color248 = "#b0b0b0"
color249 = "#bababa"
color250 = "#c4c4c4"
color251 = "#cecece"
color252 = "#d8d8d8"
color253 = "#e2e2e2"
color254 = "#ececec"
color255 = "#f6f6f6"
